image: node:latest

variables:
  PUBLIC_URL: /mp2

cache:
  paths:
  - node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - npm install
    - CI=false npm run build
    - mv dist public
    - mv build public

  artifacts:
    paths:
    - public

  only:
    - master
